### ISSUE TITLE
Are you planning to release iOS version?

### ISSUE THREAD

**Issue by narup** [curthard89/COCOA-Stuff#2]
Would be great if are planning to do it :)

**Comment by curthard89** [comment]
iOS version of what exactly?

**Comment by narup** [comment]
for readability! It seems like a very good project and lot of other people might use it.

**Comment by curthard89** [comment]
This guy has already created a port of it: https://github.com/vodkhang/iPhone-Readability-Parsing

**Comment by narup** [comment]
aah ok thanks!! for some reason i didn't find it, i was almost about to write my own.

**Comment by DZamataev** [comment]
@curthard89 @narup please take a look at my iOS-compatible implementation here https://github.com/DZamataev/DZReadability
